name: build

on:
  push:
    branches: [ "main", "experimental" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      # Force clean output and top-level node_modules
      - name: Clean npm cache
        run: npm cache clean --force

      # Set up Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies cleanly
      - name: Install dependencies
        run: npm i

      # Build project
      - name: Build streamix
        run: npm run build streamix

      # Run Jasmine tests with coverage
      - name: Run tests
        run: npm run jasmine:coverage
