name: test & coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i

      - name: Run tests with coverage
        run: npx ts-test-runner --headless --coverage

      - name: Upload coverage to Codecov
        run: |
          curl -s https://codecov.io/bash | bash -s -- -f coverage/lcov.info -r actioncrew/streamix
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
